use_default_settings: true

general:
  debug: false
  instance_name: "SearXNG"
  
search:
  formats:
    - html
    - json
    - rss

server:
  limiter: false
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "your-secret-key-here-change-this"

botdetection:
  enabled: false

# Enable additional engines that are disabled by default
engines:
  - name: yahoo
    enabled: true
  
  - name: mullvadleta
    enabled: true
    
  - name: mullvadleta brave
    enabled: true
    
  - name: bing
    enabled: true
    
  - name: qwant
    enabled: true
    
  - name: mojeek
    enabled: true
    
  - name: presearch
    enabled: true